version: "3"
services:
  nextjs-ui:
    env_file:
      - .env.development
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    container_name: next-boiler-lint
    stdin_open: true
    volumes:
      - ./:/usr/src/app
